version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: api
    depends_on:
      - mongodb
    build: 
      context: server
      dockerfile: ./dockerfile
    ports:
      - 5001:5001

  ui:
    image: ui
    depends_on:
      - api
    build:
      context: Ui
      dockerfile: ./dockerfile
    ports:
      - 5174:5174

volumes:
  mongo_volume: